import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { Button } from "@/components/ui/button";
// import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div>
      <div className="flex">

        <div className="flex-1/4 justify-center">
          <div className="flex flex-col bg-[#242424] h-screen">
            <h1 className="
                        text-center 
                        text-[45px] 
                        text-[#B1BB1E]
                        pt-14
                    ">
              Vetscanner
            </h1>

            <div className="flex flex-col justify-start pt-8">
              <Button className="
                        text-center 
                        text-[25px]
                        transform hover:scale-120 bg-transparent
                        transition duration-300 ease-in-out                        
                        p-8
                        ">
                Dashboard
              </Button>

              <Button className="
                        text-center 
                        text-[25px]
                        transform hover:scale-120 bg-transparent 
                        transition duration-300 ease-in-out                        
                        p-8
                        ">
                Patient Registration
              </Button>

              <Button className="
                        text-center 
                        text-[25px]
                        transform hover:scale-120 bg-transparent 
                        transition duration-300 ease-in-out                        
                        p-8                        
                        ">
                Scan
              </Button>

              <Button className="
                        text-center 
                        text-[25px]
                        transform hover:scale-120 bg-transparent 
                        transition duration-300 ease-in-out
                        p-8                        
                        ">
                History
              </Button>

              <Button className="
                        text-center 
                        text-[25px]
                        transform hover:scale-120 bg-transparent 
                        transition duration-300 ease-in-out
                        p-8                        
                        ">
                About us
              </Button>
            </div>


          </div>
        </div>

        <div className="flex-3/4 justify-center">
          <div className="flex flex-col bg-[#156E68E3] h-screen justify-center items-center ">
            {children}
          </div>
        </div>
      </div>
    </div>
  )
}