import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { Button } from "@/components/ui/button";

import WhiteCircle from "@/components/ui/whitecr"

// import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div>
      <div className="flex">

        <div className="flex-3/5 justify-center">
          <div className="flex flex-col bg-[#14544F] justify-center h-screen px-36">

            <div className="flex flex-col justify-center bg-[#161616] p-15 text-start text-[#B1BB1E]">

              <div className="pl-3">
                <h1 className="text-[50px] font-bold">Vetscanner</h1>
                <h2 className="text-[18px]">AI Powered Animal Diagnostics</h2>
              </div>

              <div className="flex flex-row items-center gap-3 pt-10">
                <WhiteCircle />
                <h2>AI powered disease detection</h2>
              </div>

              <div className="flex flex-row items-center gap-3 pt-5">
                <WhiteCircle />
                <h2>Smart X-Ray analytic</h2>
              </div>

              <div className="flex flex-row items-center gap-3 pt-5">
                <WhiteCircle />
                <h2>Record history</h2>
              </div>

              <div className="flex flex-row items-center gap-3 pt-5">
                <WhiteCircle />
                <h2>Report gennerating</h2>
              </div>

            </div>

          </div>
        </div>

        <div className="flex-2/5 justify-center">
          <div className="flex flex-col bg-[#156E68] h-screen justify-center items-center ">
            {children}
          </div>
        </div>
      </div>
    </div>
  )
}